name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        image-name: ['base', 'base-2']
        gdal-version: [2.4, 3.1, 3.2]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set amazonlinux version
        id: amazonlinux
        run: echo "::set-output name=version::$(if [ '${{ matrix.image-name }}' == 'base-2' ]; then echo '-al2'; else echo ''; fi)"
        shell: bash

      - name: setup Common cache
        uses: actions/cache@v2
        id: common-cache
        with:
          path: /tmp/docker
          key: ${{ matrix.image-name }}-${{ hashFiles(format('common/{0}/Dockerfile', matrix.image-name)) }}

      - name: Restore Common image
        if: steps.common-cache.outputs.cache-hit == 'true'
        run: docker image load -i /tmp/docker/${{ matrix.image-name }}.tar

      - name: Build and Cache Common image
        if: steps.common-cache.outputs.cache-hit != 'true'
        run: |
          docker build -f common/${{ matrix.image-name }}/Dockerfile -t ${{ matrix.image-name }}:build .
          mkdir -p /tmp/docker
          docker image save -o /tmp/docker/${{ matrix.image-name }}.tar ${{ matrix.image-name }}:build

      - name: setup GDAL cache
        uses: actions/cache@v2
        id: gdal-cache
        with:
          path: /tmp/docker
          key: gdal${{ matrix.gdal-version }}-${{ hashFiles(format('gdal{0}/Dockerfile', matrix.gdal-version)) }}-${{ hashFiles(format('common/{0}/Dockerfile', matrix.image-name)) }}

      - name: Restore gdal image
        if: steps.gdal-cache.outputs.cache-hit == 'true'
        run: docker image load -i /tmp/docker/${{ matrix.image-name }}-gdal${{ matrix.gdal-version }}.tar

      - name:  Build and Cache GDAL image
        if: steps.gdal-cache.outputs.cache-hit != 'true'
        run: |
          docker build \
            --build-arg IMAGE_VERSION=${{ matrix.image-name }} \
            -f gdal${{ matrix.gdal-version }}/Dockerfile \
            -t lambgeo/lambda-gdal:${{ matrix.gdal-version }}${{ steps.amazonlinux.outputs.version }} .
          mkdir -p /tmp/docker
          docker image save \
            -o /tmp/docker/${{ matrix.image-name }}-gdal${{ matrix.gdal-version }}.tar \
            lambgeo/lambda-gdal:${{ matrix.gdal-version }}${{ steps.amazonlinux.outputs.version }}

      - name: Run Tests
        run: |
          docker run \
            -v ${{ github.workspace }}:/local --rm \
            lambgeo/lambda-gdal:${{ matrix.gdal-version }}${{ steps.amazonlinux.outputs.version }} \
            sh -c "cd /local/tests && sh tests.sh"

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/master'
        run: docker push lambgeo/lambda-gdal:${{ matrix.gdal-version }}${{ steps.amazonlinux.outputs.version }}

      - name: Build Runtime and Push to DockerHub
        if: github.ref == 'refs/heads/master'
        run: |
          runtimes=$(if [ '${{ steps.amazonlinux.outputs.version }}' == '-al2' ]; then echo 'python3.8'; else echo 'python3.7'; fi)
          for runtime in ${runtimes}; do
            docker build \
              --build-arg GDAL_VERSION=${{ matrix.gdal-version }} \
              -f runtimes/${runtime} \
              -t lambgeo/lambda-gdal:${{ matrix.gdal-version }}-${runtime} .
            docker push lambgeo/lambda-gdal:${{ matrix.gdal-version }}-${runtime}
          done
