name: CI

on:
  push:
    paths:
    - '**Dockerfile'
    - 'dockerfiles/runtimes/**'
    - 'scripts/deploy.py'
    - 'scripts/create-layer.sh'
    - 'tests/*'
    branches:
    - master
    tags:
    - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        gdal-version: [3.2, 3.3]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install boto3 click

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: setup Common cache
        uses: actions/cache@v2
        id: common-cache
        with:
          path: /tmp/docker
          key: ${{ hashFiles('dockerfiles/common/Dockerfile') }}

      - name: Restore Common image
        if: steps.common-cache.outputs.cache-hit == 'true'
        run: docker image load -i /tmp/docker/common.tar

      - name: Build and Cache Common image
        if: steps.common-cache.outputs.cache-hit != 'true'
        run: |
          docker build -f dockerfiles/common/Dockerfile -t lambda-gdal:common .
          mkdir -p /tmp/docker
          docker image save -o /tmp/docker/common.tar lambda-gdal:common

      - name: setup GDAL cache
        uses: actions/cache@v2
        id: gdal-cache
        with:
          path: /tmp/docker
          key: gdal${{ matrix.gdal-version }}-${{ hashFiles(format('dockerfiles/gdal{0}/Dockerfile', matrix.gdal-version)) }}-${{ hashFiles('dockerfiles/common/Dockerfile') }}

      - name: Restore gdal image
        if: steps.gdal-cache.outputs.cache-hit == 'true'
        run: docker image load -i /tmp/docker/gdal${{ matrix.gdal-version }}.tar

      - name:  Build and Cache GDAL image
        if: steps.gdal-cache.outputs.cache-hit != 'true'
        run: |
          docker build \
            -f dockerfiles/gdal${{ matrix.gdal-version }}/Dockerfile \
            -t lambgeo/lambda-gdal:${{ matrix.gdal-version }}-al2 .
          mkdir -p /tmp/docker
          docker image save \
            -o /tmp/docker/gdal${{ matrix.gdal-version }}.tar \
            lambgeo/lambda-gdal:${{ matrix.gdal-version }}-al2

      - name: Run Tests
        run: |
          docker run \
            -v ${{ github.workspace }}:/local --rm \
            lambgeo/lambda-gdal:${{ matrix.gdal-version }}-al2 \
            sh -c "cd /local/tests && sh tests.sh"

      - name: Build and Deploy layers
        if: github.ref == 'refs/heads/master'
        run: |
          docker run \
            -v ${{ github.workspace }}:/local --rm \
            lambgeo/lambda-gdal:${{ matrix.gdal-version }}-al2 \
            sh -c "sh /local/scripts/create-layer.sh"

          python scripts/deploy.py ${{ matrix.gdal-version }} --deploy

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/master'
        run: docker push lambgeo/lambda-gdal:${{ matrix.gdal-version }}-al2

      - name: Build Runtime and Push to DockerHub
        if: github.ref == 'refs/heads/master'
        run: |
          runtimes='python3.8'
          for runtime in ${runtimes}; do
            docker build \
              --build-arg GDAL_VERSION=${{ matrix.gdal-version }} \
              -f dockerfiles/runtimes/${runtime} \
              -t lambgeo/lambda-gdal:${{ matrix.gdal-version }}-${runtime} .
            docker push lambgeo/lambda-gdal:${{ matrix.gdal-version }}-${runtime}
          done
