name: CRON

on:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: ['base', 'base-2']
        gdal-version: [2.4, 3.1, 3.2, 3.3]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set amazonlinux version
        id: amazonlinux
        run: echo "::set-output name=version::$(if [ '${{ matrix.image-name }}' == 'base-2' ]; then echo '-al2'; else echo ''; fi)"
        shell: bash

      - name: Pull GDAL Images
        run: docker pull lambgeo/lambda-gdal:${{ matrix.gdal-version }}${{ steps.amazonlinux.outputs.version }}

      - name: Pull Runtime Images
        run: |
          runtimes=$(if [ '${{ steps.amazonlinux.outputs.version }}' == '-al2' ]; then echo 'python3.8'; else echo 'python3.7'; fi)
          for runtime in ${runtimes}; do
            docker pull lambgeo/lambda-gdal:${{ matrix.gdal-version }}-${runtime}
          done
